### ISSUE TITLE
simple-storage: Input_setIpfsData and SetIpfsDataResult not implemented

### ISSUE THREAD

**Issue by kev-ngo** [Web3-API/demos#2]
In the mutation and query folders, we have an `index.ts` file for the Web3API implementation.  In our docs, we tell the user to import `Input_setIpfsData` and `SetIpfsDataResult` but these are not avaiable in the `./w3` package yet.

How do we implement this?

**Comment by dOrgJelli** [comment]
Should be fixed w/ release 0.0.1-prealpha.9
