### ISSUE TITLE
Please Review: 'completed-demos' branch > mutation and query schemas + implementation

### ISSUE THREAD

**Issue by kev-ngo** [Web3-API/demos#5]
## Why?
- Created a new folder `web3api-completed` to show the end result of going through the guide in our documentation.

## Questions
- Is `U32` an object that's available by default in AssemblyScript?
- Unsure about query implementation - please review it.
- Can you confirm that the mutation query is correct?

**Comment by dOrgJelli** [comment]
> ## Questions
> * Is `U32` an object that's available by default in AssemblyScript?

Yes `u32` is a base type in AssemblyScript: https://www.assemblyscript.org/types.html

> * Unsure about query implementation - please review it.

I reviewed and pushed a refactor, check it out

> * Can you confirm that the mutation query is correct?

Yes the mutation query looks correct! I think the next step is to create a test that hits these new functions. It might not be possible to do it with the simple recipe file, so maybe it's time to create a jest based test file? Would be cool to show viewers how you can test w/ JSON recipes, or TypeScript/JavaScript Jest test files.

**Comment by kev-ngo** [comment]
I've confirmed that this fix works!  Yes, I'll add a separate issue to create the Jest test file for these new functions.
